require("common.setup.options")
require("common.setup.disable-deprecated-notifications")
require("common.setup.lazy")
require("common.setup.keymaps")
require("common.setup.diagnostic")
require("common.setup.lazygit")
require("common.setup.yank")
require("common.setup.lsp")
