---

- name: Create database user
  community.postgresql.postgresql_user:
    name: "{{ user }}"
    password: "{{ password }}"
    login_user: "{{ POSTGRES_ADMIN_USER }}"
    login_password: "{{ POSTGRES_ADMIN_PASSWORD }}"
    login_host: "{{ HOST }}"
    login_port: "{{ POSTGRES_PORT }}"

- name: Drop database
  community.postgresql.postgresql_db:
    name: "{{ database }}"
    state: absent
    force: true
    login_user: "{{ POSTGRES_ADMIN_USER }}"
    login_password: "{{ POSTGRES_ADMIN_PASSWORD }}"
    login_host: "{{ HOST }}"
    login_port: "{{ POSTGRES_PORT }}"
  when: recreate

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ database }}"
    owner: "{{ user }}"
    encoding: UTF-8
    login_user: "{{ POSTGRES_ADMIN_USER }}"
    login_password: "{{ POSTGRES_ADMIN_PASSWORD }}"
    login_host: "{{ HOST }}"
    login_port: "{{ POSTGRES_PORT }}"

- name: Add permissions to database user
  community.postgresql.postgresql_privs:
    database: "{{ database }}"
    roles: "{{ user }}"
    privs: ALL
    grant_option: true
    type: database
    login_user: "{{ POSTGRES_ADMIN_USER }}"
    login_password: "{{ POSTGRES_ADMIN_PASSWORD }}"
    login_host: "{{ HOST }}"
    login_port: "{{ POSTGRES_PORT }}"