apiVersion: v1
kind: Pod
metadata:
  labels: { app: chachi-server-pod }
  name: chachi-server-pod
spec:
  containers:
  - name: chachi-server-filebrowser
    image: filebrowser/filebrowser:v2.24.2-s6
    resources: { limits: { cpu: 1000m, memory: 1000M } }
    envFrom: [/etc/chachi-server-env]
    ports:
    - { hostPort: 8081, containerPort: 80 }
    volumeMounts:
    - { mountPath: /srv, name: chachi-server-mnt-default }
  volumes:
  - { name: chachi-server-mnt-default, hostPath: /mnt/default }