---
- hosts: localhost
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: editorconfig, tags: ['editorconfig'] }
    - { role: fzf, tags: ['fzf'] }
    - { role: git, tags: ['git'] }
    - { role: node, tags: ['node'] }
    - { role: prompt, tags: ['prompt'] }
    - { role: ripgrep, tags: ['ripgrep'] }
    - { role: vim, tags: ['vim'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: jsconfig, tags: ['jsconfig'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: jumps, tags: ['jumps'] }
    - { role: elixir, tags: ['elixir'] }
    - { role: terminator, tags: ['terminator'] }
