---
- hosts: localhost
  roles:
    - { role: zsh, tags: ["zsh"] }
    - { role: editorconfig, tags: ["editorconfig"] }
    - { role: docker, tags: ["docker"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: git, tags: ["git"] }
    - { role: node, tags: ["node"] }
    - { role: terminator, tags: ["terminator"] }
    - { role: vim, tags: ["vim"] }
    - { role: liferay, tags: ["liferay"] }
