version: "2.4"
services:
  freshrss:
    image: freshrss/freshrss:edge
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    ports:
      - "${FRESHRSS_PORT}:80"
    environment:
      TZ: ${FRESHRSS_TZ}
      CRON_MIN: '2,32'
      FRESHRSS_INSTALL: |-
        --api_enabled
        --base_url ${BASE_URL}
        --default_user admin
        --language en
      FRESHRSS_USER: |-
        --api_password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
volumes:
  data:
  extensions:
