version: '3.4'
services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      CRON_MIN: '3,33'
    ports:
      - 10002:80
volumes:
  data:
  extensions:
