#!/bin/bash

alias cdProjects="cd $HOME/Projects"
alias cdPortal="cd $HOME/Projects/community-portal/liferay-portal"
alias cdPageEditor="cd $HOME/Projects/community-portal/liferay-portal/modules/apps/layout/layout-content-page-editor-web"
