execute pathogen#infect()
syntax on
filetype plugin indent on

set autoindent smartindent
set clipboard=unnamedplus
set noeol
set hlsearch
set ignorecase smartcase
set mouse=a
set nobackup
set noswapfile
set nowrap
set nowritebackup
set showmatch
set textwidth=80

set wildmenu
set wildignore+=*/.git/*,
set wildignore+=*/.sass-cache/*,
set wildignore+=*/build/*
set wildignore+=*/classes/*
set wildignore+=*/gradle/*
set wildignore+=*/node_modules/*
set wildignore+=*/tmp/*

let g:fzf_command_prefix = 'Fzf'
nm <silent> <C-p> :FzfGFiles<CR>
nm <silent> <C-f> :FzfRg<CR>

let g:airline_theme='minimalist'
let g:airline_section_c='%t'
let g:airline_section_z=''
let g:airline_skip_empty_sections=1

set termguicolors
set background=light
