execute pathogen#infect()
syntax on
filetype plugin indent on

set autoindent smartindent
set clipboard=unnamedplus
set cursorline
set noeol
set hlsearch
set ignorecase smartcase
set mouse=a
set nobackup
set noswapfile
set nowrap
set nowritebackup
set showmatch
set textwidth=80

set wildmenu
set wildignore+=*/.git/*,
set wildignore+=*/.sass-cache/*,
set wildignore+=*/build/*
set wildignore+=*/classes/*
set wildignore+=*/gradle/*
set wildignore+=*/node_modules/*
set wildignore+=*/tmp/*

nm <silent> <C-t> :FZF<CR>

set termguicolors
set background=light
let g:one_allow_italics = 1
let g:airline_theme='one'
colorscheme one
