#!/bin/bash
set -e
default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
current_branch=$(git branch --show-current)
if [ "$current_branch" != "$default_branch" ]; then
  echo "Error: not on $default_branch (currently on $current_branch)"
  exit 1
fi

echo "Getting your master…"

git fetch --all --prune 2>&1 | prefix fetch || exit 1
git reset --hard "origin/$default_branch" 2>&1 | prefix reset

for branch in $(git branch -vv | grep ': gone]' | awk '{print $1}'); do
  git branch -v -D "$branch" 2>&1 | prefix cleanup
done

[ -x "$HOME/.config/git/cifuentes-post.local.sh" ] && "$HOME/.config/git/cifuentes-post.local.sh" | prefix post
