#!/bin/bash

# echo "Getting your master..."
# git checkout master
# git fetch --all --prune
# git checkout upstream/master
# git branch -D master
# git checkout -b master
# git push -u -f origin master
# echo "Congrats! You have a master!"

git pull && NODE_OPTIONS="--max-old-space-size=8192" $HOME/.yarn/switch/bin/yarn typecheck:packages --errors-only
