#!/bin/bash

remote_user_and_repo=$(git remote get-url --push $1 | sed 's/.*github.com:\?\/\?//' | sed 's/\.git//');
remote_user=$(echo $remote_user_and_repo | cut -d'/' -f1)
remote_repo=$(echo $remote_user_and_repo | cut -d'/' -f2)

origin_username=$(git remote get-url origin | cut -d':' -f2 | cut -d'/' -f1);
origin_branch=$(git rev-parse --abbrev-ref HEAD);
remote_branch=$(git remote show $1 | grep 'HEAD branch' | cut -d' ' -f5);
last_commit_message=$(git log -1 --pretty=%B);

xdg-open "https://github.com/${remote_user}/${remote_repo}/compare/${remote_branch}...${origin_username}:${origin_branch}?expand=1&title=${last_commit_message}";
