#!/bin/bash

binDir=$CHACHI_PATH/home/.config/i3

while true; do
  battery=$($binDir/i3-status-bar-battery)
  brightness=$($CHACHI_PATH/seniore/target/release/seniore linux get-brightness)
  date=$($CHACHI_PATH/seniore/target/release/seniore linux get-date)
  woffu=$($CHACHI_PATH/seniore/target/release/seniore woffu get-status)

  echo "${woffu} ${battery} ${brightness} ${volume} ${date}"
  sleep 2
done
