[package]
name = "seniore"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.59"
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
notify-rust = "4"
ansi-escapes = "0.1.1"
home = "0.5.4"
