---
- name: Clone fzf repository
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
  register: fzf_repo_status

- name: Install fzf
  shell: ./install --all
  args:
    chdir: "{{ ansible_env.HOME }}/.fzf"
  when: fzf_repo_status.changed
