---
- name: Install git and git-extras
  become: yes
  pacman:
    name: git
    state: present
    update_cache: yes

- name: Copy git config files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items:
    - gh.json
    - gitconfig
    - gitignore-global
