window:
  gtk_theme_variant: dark

font:
  normal:
    family: Victor Mono
    style: medium
  bold:
    family: Victor Mono
  italic:
    family: Victor Mono
  bold_italic:
    family: Victor Mono
  size: 11.0
  draw_bold_text_with_bright_colors: false

background_opacity: 0.97
live_config_reload: true
