window:
  decorations_theme_variant: light
  dynamic_title: true
  opacity: 1.0

font:
  normal:
    family: Fira Code
    style: Regular
  size: 8.5
  draw_bold_text_with_bright_colors: true

bell:
  duration: 100

cursor:
  blinking: On
  style: Block

live_config_reload: true

# Catppuccin latte!

colors:
  primary:
    background: '#EFF1F5'
    foreground: '#4C4F69'
    dim_foreground: '#4C4F69'
    bright_foreground: '#4C4F69'

  cursor:
    text: '#EFF1F5'
    cursor: '#DC8A78'

  vi_mode_cursor:
    text: '#EFF1F5'
    cursor: '#7287FD'

  search:
    matches:
      foreground: '#EFF1F5'
      background: '#6C6F85'
    focused_match:
      foreground: '#EFF1F5'
      background: '#40A02B'
    footer_bar:
      foreground: '#EFF1F5'
      background: '#6C6F85'

  hints:
    start:
      foreground: '#EFF1F5'
      background: '#DF8E1D'
    end:
      foreground: '#EFF1F5'
      background: '#6C6F85'

  selection:
    text: '#EFF1F5'
    background: '#DC8A78'

  normal:
    black: '#5C5F77'
    red: '#D20F39'
    green: '#40A02B'
    yellow: '#DF8E1D'
    blue: '#1E66F5'
    magenta: '#EA76CB'
    cyan: '#179299'
    white: '#ACB0BE'

  bright:
    black: '#6C6F85'
    red: '#D20F39'
    green: '#40A02B'
    yellow: '#DF8E1D'
    blue: '#1E66F5'
    magenta: '#EA76CB'
    cyan: '#179299'
    white: '#BCC0CC'

  dim:
    black: '#5C5F77'
    red: '#D20F39'
    green: '#40A02B'
    yellow: '#DF8E1D'
    blue: '#1E66F5'
    magenta: '#EA76CB'
    cyan: '#179299'
    white: '#ACB0BE'

  indexed_colors:
    - { index: 16, color: '#FE640B' }
    - { index: 17, color: '#DC8A78' }
