source-file ~/.config/tmux/conf.d/100-options.conf
source-file ~/.config/tmux/conf.d/200-theme.conf
source-file ~/.config/tmux/conf.d/300-keybindings.conf
source-file ~/.config/tmux/conf.d/400-vim-navigator.conf
source-file ~/.config/tmux/conf.d/500-lazygit.conf
