---
- name: Install tmux
  become: yes
  apt:
    name: tmux
    state: present

- name: Copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: Autostart tmux
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    line: "if command -v tmux &> /dev/null && [ -z \"$TMUX\" ]; then tmux attach -t default || tmux new -s default; fi"
