---
- name: Install tmux
  become: yes
  apt:
    name: tmux
    state: present

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux-plugin-manager"

- name: Copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: Don't autostart tmux
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: absent
    line: "if command -v tmux &> /dev/null && [ -z \"$TMUX\" ]; then tmux attach -t default || tmux new -s default; fi"
