---
- name: Install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: Add Nodesource apt key
  become: yes
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"

- name: Install NodeJS and NPM
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: Create .npm-global directory
  file:
    path: "{{ ansible_env.HOME }}/.npm-global"
    state: directory

- name: Create .npmrc
  file:
    path: "{{ ansible_env.HOME }}/.npmrc"
    state: touch

- name: Set npm prefix to .npm-global
  lineinfile:
    path: "{{ ansible_env.HOME }}/.npmrc"
    line: "prefix={{ ansible_env.HOME }}/.npm-global"
    state: present

- name: Add .npm-global to $PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=$HOME/.npm-global/bin:$PATH"
    state: present

- name: Add .npm-global to $NODE_PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export NODE_PATH=/usr/lib/node_modules:$HOME/.npm-global/lib/node_modules:$NODE_PATH"
    state: present

- name: Upgrade NPM
  npm:
    name: npm
    global: yes
    state: latest

- name: Install some utils
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - prettier
    - http-server
    - browser-sync
    - eslint
