---
- name: Install NodeJS and NPM
  become: yes
  pacman:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: Create .npm-global directory
  file:
    path: "{{ ansible_env.HOME }}/.npm-global"
    state: directory

- name: Create .npmrc
  file:
    path: "{{ ansible_env.HOME }}/.npmrc"
    state: touch

- name: Set npm prefix to .npm-global
  lineinfile:
    path: "{{ ansible_env.HOME }}/.npmrc"
    line: "prefix={{ ansible_env.HOME }}/.npm-global"
    state: present

- name: Install some utils
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - prettier
    - http-server
    - browser-sync
    - eslint
    - javascript-typescript-langserver
    - typescript
    - neovim
    - execa
    - "@octokit/rest"
    - jira-client
    - chalk
