apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/p2kmgcl/Projects/chachi-shell/liferay:z
  creationTimestamp: '2024-02-06T14:15:30Z'
  labels:
    app: liferay-portal-container-pod
  name: liferay-portal-container-pod
spec:
  containers:
    - name: liferay-portal-container
      image: docker.io/liferay/portal:latest
      tty: true
      stdin: true
      livenessProbe:
        exec:
          command: ['curl', '-Is', 'http://localhost:8080']
        initialDelaySeconds: 60
        periodSeconds: 10
        retries: 10
      ports:
        - containerPort: 8080
          hostPort: 8081
      volumeMounts:
        - mountPath: /mnt/liferay/files
          name: liferay-portal-container-files-pvc
    - name: liferay-portal-container-database
      image: docker.io/library/mysql:5.7
      args:
        - mysqld
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
      env:
        - name: MYSQL_DATABASE
          value: liferay_portal
        - name: MYSQL_ROOT_PASSWORD
          value: root
      livenessProbe:
        exec:
          command: ['mysqladmin', '-uroot', '-proot', 'ping', '-h', 'localhost']
        initialDelaySeconds: 10
        periodSeconds: 10
        retries: 10
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: liferay-portal-container-database-pvc
  volumes:
    - name: liferay-portal-container-files-pvc
      hostPath:
        path: /home/p2kmgcl/Projects/chachi-shell/liferay
        type: Directory
    - name: liferay-portal-container-database-pvc
      persistentVolumeClaim:
        claimName: liferay-portal-container-database
