live_config_reload = true

[bell]
duration = 100

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 10

[font.normal]
family = "Victor Mono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[scrolling]
history = 0

[window]
decorations = "full"
decorations_theme_variant = "Light"
dynamic_padding = true
dynamic_title = false
opacity = 0.85
resize_increments = true

[colors]
draw_bold_text_with_bright_colors = true

# https://github.com/alacritty/alacritty-theme/blob/master/themes/catppuccin_latte.toml

[colors.primary]
background = '#EFF1F5'
foreground = '#4C4F69'
dim_foreground = '#4C4F69'
bright_foreground = '#4C4F69'

[colors.cursor]
text = '#EFF1F5'
cursor = '#DC8A78'

[colors.vi_mode_cursor]
text = '#EFF1F5'
cursor = '#7287FD'

[colors.search.matches]
foreground = '#EFF1F5'
background = '#6C6F85'

[colors.search.focused_match]
foreground = '#EFF1F5'
background = '#40A02B'

[colors.footer_bar]
foreground = '#EFF1F5'
background = '#6C6F85'

[colors.hints.start]
foreground = '#EFF1F5'
background = '#DF8E1D'

[colors.hints.end]
foreground = '#EFF1F5'
background = '#6C6F85'

[colors.selection]
text = '#EFF1F5'
background = '#DC8A78'

[colors.normal]
black = '#5C5F77'
red = '#D20F39'
green = '#40A02B'
yellow = '#DF8E1D'
blue = '#1E66F5'
magenta = '#EA76CB'
cyan = '#179299'
white = '#ACB0BE'

[colors.bright]
black = '#6C6F85'
red = '#D20F39'
green = '#40A02B'
yellow = '#DF8E1D'
blue = '#1E66F5'
magenta = '#EA76CB'
cyan = '#179299'
white = '#BCC0CC'

[colors.dim]
black = '#5C5F77'
red = '#D20F39'
green = '#40A02B'
yellow = '#DF8E1D'
blue = '#1E66F5'
magenta = '#EA76CB'
cyan = '#179299'
white = '#ACB0BE'
