[env]
TERM = "xterm-256color"

[bell]
duration = 100

[cursor.style]
blinking = "Always"
shape = "Block"

[general]
live_config_reload = true

[font]
size = 16

[font.normal]
family = "M+1Code Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[scrolling]
history = 99999

[window]
blur = false
decorations = "full"
decorations_theme_variant = "Light"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
option_as_alt = "Both"
resize_increments = true
# startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true

# https://github.com/alacritty/alacritty-theme/blob/master/themes/github_light_colorblind.toml

[colors.primary]
background = '#ffffff'
foreground = '#0E1116'

[colors.normal]
black   = '#24292f'
red     = '#cf222e'
green   = '#116329'
yellow  = '#4d2d00'
blue    = '#0969da'
magenta = '#8250df'
cyan    = '#1b7c83'
white   = '#6e7781'

[colors.bright]
black   = '#57606a'
red     = '#a40e26'
green   = '#1a7f37'
yellow  = '#633c01'
blue    = '#218bff'
magenta = '#a475f9'
cyan    = '#3192aa'
white   = '#8c959f'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#a40e26'
