[env]
TERM = "xterm-256color"

[bell]
duration = 100

[cursor.style]
blinking = "Always"
shape = "Block"

[general]
live_config_reload = true

[font]
size = 16

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.offset]
x = 0
y = 4

[scrolling]
history = 99999

[window]
blur = false
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
option_as_alt = "Both"
resize_increments = true
# startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true

# https://github.com/alacritty/alacritty-theme/blob/master/themes/github_dark_colorblind.toml

[colors.primary]
background = '#0d1117'
foreground = '#b3b1ad'

[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#39c5cf'
white   = '#b1bac4'

[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'
