- name: Check lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ USER }}"
  register: linger_result

- name: Enable lingering
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ USER }}"
  when: not linger_result.stat.exists

- name: Reboot
  become: true
  ansible.builtin.reboot:
  when: not linger_result.stat.exists
