-- Highlight, edit, and navigate code
return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPost" },
  build = ":TSUpdate",
  dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
  config = function()
    require("nvim-treesitter.install").prefer_git = true
    ---@diagnostic disable-next-line: missing-fields
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "astro",
        "bash",
        "css",
        "dockerfile",
        "editorconfig",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "sway",
        "tmux",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
      },
      auto_install = true,
      highlight = { enable = true },
      incremental_selection = { enable = true },
      indent = { enable = true },
      textobjects = {
        move = {
          enable = true,
          set_jumps = true,
          goto_next_start = {
            ["]a"] = "@attribute.outer",
            ["]c"] = "@class.outer",
            ["]f"] = "@function.outer",
            ["]p"] = "@parameter.inner",
          },
          goto_next_end = {
            ["]A"] = "@attribute.outer",
            ["]C"] = "@class.outer",
            ["]F"] = "@function.outer",
            ["]P"] = "@parameter.inner",
          },
          goto_previous_start = {
            ["[a"] = "@attribute.outer",
            ["[c"] = "@class.outer",
            ["[f"] = "@function.outer",
            ["[p"] = "@parameter.inner",
          },
          goto_previous_end = {
            ["[A"] = "@attribute.outer",
            ["[C"] = "@class.outer",
            ["[F"] = "@function.outer",
            ["[P"] = "@parameter.inner",
          },
        },
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            ["aa"] = "@attribute.outer",
            ["ia"] = "@attribute.inner",
            ["ac"] = "@class.outer",
            ["ic"] = "@class.inner",
            ["af"] = "@function.outer",
            ["if"] = "@function.inner",
            ["ap"] = "@parameter.outer",
            ["ip"] = "@parameter.inner",
          },
        },
      },
    })
  end,
}
