---

- name: Add neovim ppa
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/stable
    update_cache: yes

- name: Install neovim and related
  become: yes
  apt:
    name: ['neovim', 'python-dev', 'python-pip', 'python3-dev', 'python3-pip']
    state: present

- name: Create .config/nvim/autoload
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/autoload"
    state: directory

- name: Create .config/nvim/bundle
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/bundle"
    state: directory

- name: Copy init.vim
  copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Download pathogen
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/pathogen.vim"

- name: Download vim plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/bundle/{{ item.name }}"
  with_items:
    - name: autojump
      repo: https://github.com/philip-karlsson/aerojump.nvim
