---

- name: Add neovim ppa
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/stable
    update_cache: yes

- name: Install neovim, python-dev and python-pip
  become: yes
  apt:
    name: ['neovim', 'python-dev', 'python-pip', 'python3-dev', 'python3-pip']
    state: present

- name: Add neovim python support
  pip:
    executable: "{{ item }}"
    name: neovim
    state: present
    extra-args: --user
  with_items:
    - pip2
    - pip3

- name: Create .config/nvim/
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: Copy init.vim
  copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Create .local/share/nvim/site/autoload/
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Create .config/nvim/plugged/
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/plugged"
    state: directory

- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
