---

- name: Create volume
  containers.podman.podman_volume:
    name: "{{ POSTGRES_VOLUME }}"

- name: Run postgres container
  containers.podman.podman_container:
    name: postgres
    image: docker.io/postgres:15.4-bullseye
    healthcheck: "/usr/bin/pg_isready"
    ports:
      - "{{ POSTGRES_PORT }}:5432"
    volumes:
      - "{{ POSTGRES_VOLUME }}:/var/lib/postgresql/data"
    env:
      POSTGRES_PASSWORD: "{{ POSTGRES_ADMIN_PASSWORD }}"
      POSTGRES_USER: "{{ POSTGRES_ADMIN_USER }}"

- name: Wait until database is ready
  ansible.builtin.command: "podman wait --condition healthy postgres"

- name: Run pgadmin4 container
  containers.podman.podman_container:
    name: pgadmin4
    image: docker.io/dpage/pgadmin4:7.5
    ports:
      - "{{ POSTGRES_ADMIN_GUI_PORT }}:80"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ POSTGRES_ADMIN_GUI_EMAIL }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ POSTGRES_ADMIN_GUI_PASSWORD }}"
      PGADMIN_DISABLE_POSTFIX: true

- name: Publish pgadmin4 port
  become: true
  ansible.posix.firewalld:
    zone: FedoraServer
    port: "{{ POSTGRES_ADMIN_GUI_PORT }}/tcp"
    permanent: true
    immediate: true
    state: enabled
