version: '3'
services:
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant
    volumes:
      - hass_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mariadb
      - mosquitto
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: '${HA_MYSQL_PASSWORD}'
      PUID: 1000
      PGID: 1000
    volumes:
      - mariadb_config:/config
    ports:
      - '3306:3306'
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - '1880:1880'
    volumes:
      - nodered_data:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: 'Europe/Madrid'
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
    volumes:
      - 'mosquitto_config:/mosquitto/config'
      - 'mosquitto_data:/mosquitto/data'
      - 'mosquitto_log:/mosquitto/log'
    environment:
      - TZ=Europe/Madrid
    user: '${PUID}:${PGID}'
  hass-configurator:
    image: 'causticlab/hass-configurator-docker:arm'
    container_name: hass-configurator
    restart: unless-stopped
    ports:
      - '3218:3218/tcp'
    depends_on:
      - homeassistant
    volumes:
      - 'configurator_config:/config'
      - 'hass_config:/hass-config'
    user: '${PUID}:${PGID}'
volumes:
  hass_config:
  configurator_config:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  nodered_data:
  mariadb_config:
