#!/usr/bin/node

const path = require('path')
const fs = require('fs')
const os = require('os')
const execa = require('execa')
const {Octokit} = require('@octokit/rest')
const JiraApi = require('jira-client')

const CONFIG = JSON.parse(fs.readFileSync(path.resolve(os.homedir(), '.gh-wrapper.json'), 'utf-8'))
const BRANCH_NAME_PATTERN = /^pr\/([a-zA-Z0-9-]+)\/([0-9]+)$/i
const COMMIT_MESSAGE_PATTERN = /^(LPS-[0-9]+)/i

const octokit = new Octokit({ auth: CONFIG.GITHUB_TOKEN })

const jira = new JiraApi({
  protocol: 'https',
  host: CONFIG.JIRA_URL,
  username: CONFIG.JIRA_USER,
  password: CONFIG.JIRA_PASSWORD,
  strictSSL: true,
  apiVersion: '2',
});

let issueId = ''
let localOwner = ''
let repo = ''

const main = async () => {
  const data = /:([^\/]+)\/([^\.]+)\.git$/.exec(
    (await execa.command('git remote get-url origin')).stdout,
  );

  localOwner = data[1]
  repo = data[2]

  switch (process.argv[2]) {
    case 'checkout-pull-request': checkoutPullRequest(process.argv[3]); break;
    case 'list-pull-requests': listPullRequests(); break;
    case 'send-pull-request': sendPullRequest(process.argv[3]); break;
    default: break;
  }
}

const listPullRequests = async () => {
  const {data: prs} = await octokit.pulls.list({ owner: localOwner, repo })

  prs.forEach(pr => {
    console.log(`#${pr.number} ${pr.title} (@${pr.user.login})`)
  })
}

const checkoutPullRequest = async (number) => {
  const {data: prs} = await octokit.pulls.list({ owner: localOwner, repo })
  const pr = prs.find(pr => pr.number == number)

  await execa.command(`git pr ${pr.html_url}`)
  await execa.command(`git branch --move pr/${pr.user.login}/${pr.number}`)
}

const sendPullRequest = async (owner) => {
  const {stdout: title} = await execa.command('git log -1 --pretty=%s')
  const {stdout: branch} = await execa.command('git rev-parse --abbrev-ref HEAD')
  let sourceOwner = '';
  let sourceNumber = '';
  let body = '';

  if (BRANCH_NAME_PATTERN.test(branch)) {
    const data = BRANCH_NAME_PATTERN.exec(branch)

    sourceOwner = data[1]
    sourceNumber = data[2]
    body = `/cc @${sourceOwner}`
  }

  await execa.command(`git push --force origin ${branch}`)

  const pr = await octokit.pulls.create({
    owner,
    repo,
    title,
    head: `${localOwner}:${branch}`,
    base: 'master',
    body
  })

  if (sourceOwner && sourceNumber) {
    await octokit.issues.createComment({
      owner: localOwner,
      repo,
      issue_number: sourceNumber,
      body: pr.data.html_url
    })

    await octokit.pulls.update({
      owner: localOwner,
      repo,
      pull_number: sourceNumber,
      state: 'closed'
    })
  }

  if (owner === 'liferay-echo') {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: pr.data.number,
      body: 'ci:forward'
    })
  }

  if (COMMIT_MESSAGE_PATTERN.test(title)) {
    const data = COMMIT_MESSAGE_PATTERN.exec(title);

    issueId = data[1];

    console.log(`https://${CONIFG.JIRA_URL}/browse/${issueId}`);

    await jira.updateIssue(issueId, {
      fields: {
        customfield_10421: pr.data.html_url
      }
    })

    if (CONFIG.GITHUB_USER_TO_JIRA_USER[owner]) {
      await jira.updateAssignee(
        issueId,
        CONFIG.GITHUB_USER_TO_JIRA_USER[owner]
      )
    } else {
      console.log(`No JIRA user found for ${owner}`)
    }
  }

  await execa.command('git checkout master')
  await execa.command(`git branch -D ${branch}`)

  console.log(pr.data.html_url)
}

main();
