---
- name: Create Projects/community-portal
  file:
    path: "{{ ansible_env.HOME }}/Projects/community-portal"
    state: directory

- name: Install gradle-launcher
  npm:
    name: gradle-launcher
    global: yes
    state: present

- name: Install Java
  become: yes
  apt:
    name:
      [
        "openjdk-8-jdk",
        "openjdk-8-dbg",
        "openjdk-8-doc",
        "openjdk-8-jre",
        "openjdk-8-source",
      ]
    state: present
    update_cache: yes

- name: Install Apache ANT
  become: yes
  apt:
    name: ant
    state: present
    update_cache: yes

- name: Clone liferay-portal
  git:
    repo: git@github.com:p2kmgcl/liferay-portal.git
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-portal"
    update: false

- name: Clone liferay-binaries-2020
  git:
    repo: https://github.com/liferay/liferay-binaries-cache-2020.git
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-binaries-cache-2020"
    update: false

- name: Copy editorconfig to modules/apps/.editorconfig
  copy:
    src: editorconfig
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-portal/modules/apps/.editorconfig"

- name: Copy portal-ext.properties
  copy:
    src: portal-ext.properties
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/portal-ext.properties"

- name: Copy .bashrc-liferay file
  copy:
    src: bashrc-liferay
    dest: "{{ ansible_env.HOME }}/.bashrc-liferay"

- name: Link .bashrc to liferay
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    line: "source ~/.bashrc-liferay"
