---
- name: Create Projects/community-portal
  file:
    path: "{{ ansible_env.HOME }}/Projects/community-portal"
    state: directory

- name: Install gradle-launcher
  npm:
    name: gradle-launcher
    global: yes
    state: present

- name: Install Java and ANT
  become: yes
  pacman:
    name:
      ["ant", "jre8-openjdk", "jdk8-openjdk", "openjdk8-doc", "openjdk8-src"]
    state: present
    update_cache: yes

- name: Clone liferay-portal
  git:
    repo: git@github.com:p2kmgcl/liferay-portal.git
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-portal"
    update: false

- name: Clone liferay-binaries-2020
  git:
    repo: https://github.com/liferay/liferay-binaries-cache-2020.git
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-binaries-cache-2020"
    update: false

- name: Copy VSCode workspace to community-portal/liferay-portal.code-workspace
  copy:
    src: liferay-portal.code-workspace
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-portal.code-workspace"

- name: Copy editorconfig to modules/apps/.editorconfig
  copy:
    src: editorconfig
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-portal/modules/apps/.editorconfig"

- name: Copy portal-ext.properties
  copy:
    src: portal-ext.properties
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/portal-ext.properties"

- name: Copy typing files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/Projects/community-portal/liferay-portal/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/types/{{ item }}"
  with_items:
    - Liferay.d.ts
    - LiferayGlobal.d.ts
