---

- name: Create volume
  containers.podman.podman_volume:
    name: "{{ POSTGRES_VOLUME }}"
    recreate: "{{ RESET }}"

- name: Create database
  ansible.builtin.include_tasks: create-postgres-database.yml
  vars:
    database: "{{ NEXTCLOUD_DATABASE }}"
    user: "{{ NEXTCLOUD_DATABASE_USER }}"
    password: "{{ NEXTCLOUD_DATABASE_PASSWORD }}"

- name: Run container
  containers.podman.podman_container:
    name: nextcloud
    image: docker.io/nextcloud:27.0.2
    ports:
      - "{{ NEXTCLOUD_PORT }}:80"
    volumes:
      - "{{ NEXTCLOUD_VOLUME }}:/var/www/html"
    env:
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ HOST }}"
      PHP_UPLOAD_LIMIT: 50G
      POSTGRES_DB: "{{ NEXTCLOUD_DATABASE }}"
      POSTGRES_HOST: "{{ HOST }}:{{ POSTGRES_PORT }}"
      POSTGRES_PASSWORD: "{{ NEXTCLOUD_DATABASE_PASSWORD }}"
      POSTGRES_USER: "{{ NEXTCLOUD_DATABASE_USER }}"