---
- name: Create .fonts/FiraCode directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts/FiraCode"
    state: directory
  register: fira_code_font

- name: Download Fira Code font
  unarchive:
    src: https://github.com/tonsky/FiraCode/releases/download/1.207/FiraCode_1.207.zip
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/.fonts/FiraCode"
  when: fira_code_font.changed

- name: Create .fonts/Inconsolata directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts/Inconsolata"
    state: directory
  register: inconsolata_font

- name: Download Inconsolata font
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.fonts/Inconsolata"
  when: inconsolata_font.changed
  with_items:
    - https://github.com/googlefonts/Inconsolata/releases/download/v2.012/Inconsolata-Bold.ttf
    - https://github.com/googlefonts/Inconsolata/releases/download/v2.012/Inconsolata-Regular.ttf

- name: Create .fonts/VictorMono directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts/VictorMono"
    state: directory
  register: victor_mono_font

- name: Download Victor Mono font
  unarchive:
    src: https://rubjo.github.io/victor-mono/VictorMonoAll.zip
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/.fonts/VictorMono"
  when: victor_mono_font.changed
